export const USER_LOGIN_REQUEST = "USER_LOGIN_REQUEST";
export const USER_LOGIN_REQUEST_SUCCESS = "USER_LOGIN_REQUEST_SUCCESS";
export const USER_LOGIN_REQUEST_FAIL = "USER_LOGIN_REQUEST_FAIL";
export const USER_LOGOUT = "USER_LOGOUT";

export const USER_REGISTER_REQUEST = "USER_REGISTER_REQUEST";
export const USER_REGISTER_REQUEST_SUCCESS = "USER_REGISTER_REQUEST_SUCCESS";
export const USER_REGISTER_REQUEST_FAIL = "USER_REGISTER_REQUEST_FAIL";

export const USER_DETAILS_REQUEST = "USER_DETAILS_REQUEST";
export const USER_DETAILS_REQUEST_SUCCESS = "USER_DETAILS_REQUEST_SUCCESS";
export const USER_DETAILS_REQUEST_FAIL = "USER_DETAILS_REQUEST_FAIL";
export const USER_DETAILS_RESET = "USER_DETAILS_RESET";

export const UPDATE_USER_DETAILS = "UPDATE_USER_DETAILS";
export const UPDATE_USER_DETAILS_SUCCESS = "UPDATE_USER_DETAILS_SUCCESS";
export const UPDATE_USER_DETAILS_FAIL = "UPDATE_USER_DETAILS_FAIL";
export const UPDATE_USER_RESET = "UPDATE_USER_RESET";

export const GET_ALL_USERS = "GET_ALL_USERS";
export const GET_ALL_USERS_SUCCESS = "GET_ALL_USERS_SUCCESS";
export const GET_ALL_USERS_FAIL = "GET_ALL_USERS_FAIL";
export const ALL_USERS_RESET = "ALL_USERS_RESET";

export const DELETE_USER = "DELETE_USER";
export const DELETE_USER_SUCCESS = "DELETE_USER_SUCCESS";
export const DELETE_USER_FAIL = "DELETE_USER_FAIL";
