export const ORDER_CREATE_REQUEST = "ORDER_CREATE_REQUEST";
export const ORDER_CREATE_REQUEST_SUCCESS = "ORDER_CREATE_REQUEST_SUCCESS";
export const ORDER_CREATE_REQUEST_FAIL = "ORDER_CREATE_REQUEST_FAIL";

export const GET_ORDER_REQUEST = "GET_ORDER_REQUEST";
export const GET_ORDER_REQUEST_SUCCESS = "GET_ORDER_REQUEST_SUCCESS";
export const GET_ORDER_REQUEST_FAIL = "GET_ORDER_REQUEST_FAIL";

export const ORDER_PAY_REQUEST = "ORDER_PAY_REQUEST";
export const ORDER_PAY_REQUEST_SUCCESS = "ORDER_PAY_REQUEST_SUCCESS";
export const ORDER_PAY_REQUEST_FAIL = "ORDER_PAY_REQUEST_FAIL";
export const ORDER_PAY_RESET = "ORDER_PAY_RESET";

export const USER_ORDER_REQUEST = "USER_ORDER_REQUEST";
export const USER_ORDER_REQUEST_SUCCESS = "USER_ORDER_REQUEST_SUCCESS";
export const USER_ORDER_REQUEST_FAIL = "USER_ORDER_REQUEST_FAIL";
export const USER_ORDER_RESET = "USER_ORDER_RESET";

export const GET_ALL_ORDERS = "GET_ALL_ORDERS";
export const GET_ALL_ORDERS_SUCCESS = "GET_ALL_ORDERS_SUCCESS";
export const GET_ALL_ORDERS_FAIL = "GET_ALL_ORDERS_FAIL";

export const UPDATE_ORDER_DELIVER = "UPDATE_ORDER_DELIVER";
export const UPDATE_ORDER_DELIVER_SUCCESS = "UPDATE_ORDER_DELIVER_SUCCESS";
export const UPDATE_ORDER_DELIVER_FAIL = "UPDATE_ORDER_DELIVER_FAIL";
export const UPDATE_ORDER_DELIVER_RESET = "UPDATE_ORDER_DELIVER_RESET";
