export const PRODUCT_LIST_REQUEST = "PRODUCT_LIST_REQUEST";
export const PRODUCT_LIST_REQUEST_SUCCESS = "PRODUCT_LIST_REQUEST_SUCCESS";
export const PRODUCT_LIST_REQUEST_FAIL = "PRODUCT_LIST_REQUEST_FAIL";

export const PRODUCT_DETAILS_REQUEST = "PRODUCT_DETAILS_REQUEST";
export const PRODUCT_DETAILS_REQUEST_SUCCESS =
  "PRODUCT_DETAILS_REQUEST_SUCCESS";
export const PRODUCT_DETAILS_REQUEST_FAIL = "PRODUCT_LIST_REQUEST_FAIL";

export const PRODUCT_DELETE_REQUEST = "PRODUCT_DELETE_REQUEST";
export const PRODUCT_DELETE_REQUEST_SUCCESS = "PRODUCT_DELETE_REQUEST_SUCCESS";
export const PRODUCT_DELETE_REQUEST_FAIL = "PRODUCT_DELETE_REQUEST_FAIL";

export const CREATE_PRODUCT_REQUEST = "CREATE_PRODUCT_REQUEST";
export const CREATE_PRODUCT_REQUEST_SUCCESS = "CREATE_PRODUCT_REQUEST_SUCCESS";
export const CREATE_PRODUCT_REQUEST_FAIL = "CREATE_PRODUCT_REQUEST_FAIL";
export const CREATE_PRODUCT_RESET = "CREATE_PRODUCT_RESET";

export const EDIT_PRODUCT = "EDIT_PRODUCT";
export const EDIT_PRODUCT_SUCCESS = "EDIT_PRODUCT_SUCCESS";
export const EDIT_PRODUCT_FAIL = "EDIT_PRODUCT_FAIL";
export const EDIT_PRODUCT_RESET = "EDIT_PRODUCT_RESET";

export const CREATE_PRODUCT_REVIEW_REQUEST = "CREATE_PRODUCT_REVIEW_REQUEST";
export const CREATE_PRODUCT_REVIEW_REQUEST_SUCCESS =
  "CREATE_PRODUCT_REVIEW_REQUEST_SUCCESS";
export const CREATE_PRODUCT_REVIEW_REQUEST_FAIL =
  "CREATE_PRODUCT_REVIEW_REQUEST_FAIL";
export const CREATE_PRODUCT_REVIEW_RESET = "CREATE_PRODUCT_REVIEW_RESET";
